routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('home.index');
});

Route::get('/home', 'HomeController@index');

Route::get('/register', 'AuthController@index');

Route::post('/welcome', 'AuthController@kirim');

Route::get('/table', function () {
    return view('table.table1');
});

Route::get('datatable', function () {
    return view('table.index');
});

Route::get('/cast', 'CastController@index');
Route::get('/cast/create', 'CastController@create');
Route::post('/cast', 'CastController@store');
Route::get('/cast/{cast_id}', 'CastController@show');
Route::get('/cast/{cast_id}/edit', 'CastController@edit');
Route::put('/cast/{cast_id}', 'CastController@update');
Route::delete('/cast/{cast_id}', 'CastController@destroy');

// genre
Route::get('/genre', 'GenreController@index');
Route::get('/genre/create', 'GenreController@create');
Route::post('/genre', 'GenreController@store');
Route::get('/genre/{genre_id}', 'GenreController@show');
Route::get('/genre/{genre_id}/edit', 'GenreController@edit');
Route::put('/genre/{genre_id}', 'GenreController@update');
Route::delete('/genre/{genre_id}', 'GenreController@delete');



// film
Route::resource('film', 'FilmController');

app/Film.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Film extends Model
{
    protected $table = 'film';
    protected $fillable = ['judul','ringkasan','tahun','genre_id','poster'];
}

app/Http/Controllers/FilmController.php
<?php

namespace App\Http\Controllers;

use App\Film;
use App\Genre;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class FilmController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $film = Film::all();
        return view('film.index', compact('film'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $genre = Genre::all();
        return view('film.create', compact('genre'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $tahun = date('Y');
        $messages = [
            'required' => ':attribute wajib diisi.',
            'max' => ':attribute maksimum :max.',
        ];
        $validator = Validator::make($request->all(), [
            'judul' => 'required',
            'ringkasan' => 'required',
            'tahun' => "required|numeric|max:$tahun",
            'genre_id' => 'required',
            'poster' => 'required|mimes:jpg,jpeg,png|max:2200'
        ], $messages);

        if ($validator->fails()) {
            return redirect()
                ->back()
                ->withErrors($validator)
                ->withInput();
        }

        $poster = $request->file('poster');
        // jika poster nya gaada
        if (!$poster) {
            return redirect()
                ->back()
                ->withErrors(['poster' => "Harap masukkan file!"])
                ->withInput();
            // sebenernya ngasih required disana udah cukup, mungkin jika posternya gaada kamu mau melakukan sesuatu, aku kasih caranya
        } else {
            // jika posternya ada
            $nama_file = uniqid('img_') . $poster->getClientOriginalName();
            // file nya mau ditaro kemana,
            $lokasi_file = public_path() . '/uploads/film/';
            $poster->move($lokasi_file, $nama_file);

            $film = Film::create([
                'judul' => $request->judul,
                'ringkasan' => $request->ringkasan,
                'tahun' => $request->tahun,
                'genre_id' => $request->genre_id,
                'poster' => $nama_file,
            ]);
        }

        return redirect()->route('film.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $film = Film::find($id);
        return view('film.show', compact('film'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $genre = Genre::all();
        $film = Film::find($id);
        return view('film.edit', compact('film', 'genre'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // update data
        // bikin validasinya dulu,
        $film = Film::find($id);
        $tahun = date('Y');
        $messages = [
            'required' => ':attribute wajib diisi.',
            'max' => ':attribute maksimum :max.',
        ];
        $validator = Validator::make($request->all(), [
            'judul' => 'required',
            'ringkasan' => 'required',
            'tahun' => "required|numeric|max:$tahun",
            'genre_id' => 'required',
            'poster' => 'mimes:jpg,jpeg,png|max:2200' //gaperlu required, siapa tau gamau ganti poster.
        ], $messages);

        if ($validator->fails()) {
            return redirect()
                ->back()
                ->withErrors($validator)
                ->withInput();
        }

        $film->update([  //sama aja
            'judul' => $request->judul,
            'ringkasan' => $request->ringkasan,
            'tahun' => $request->tahun,
            'genre_id' => $request->genre_id,
        ]);

        // cek image
        $poster = $request->file('poster');
        if ($poster) {
            // jika ada poster, kalo gaada ya biarin aja
            // jika posternya ada
            $nama_file = uniqid('img_') . $poster->getClientOriginalName();
            // file nya mau ditaro kemana,
            $lokasi_file = public_path() . '/uploads/film/';
            $poster->move($lokasi_file, $nama_file); //ini kan buat mindahin file baru

            unlink($lokasi_file . $film->poster); //public/uploads/film/nama_file.jpg . ini buat menghapus file yg lama

            $film->update(['poster' => $nama_file]);
        }
        return redirect()->route('film.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // dd($id);
        Film::destroy($id);
        return redirect()->route('film.index');
    }
}

resources/views/film/create.blade.php
@extends('layouts.master')

@section('judul')
Halaman Tambah Film
@endsection

@section('konten')

<h2>Tambah Data Film</h2>
<form action="{{ route('film.store') }}" enctype="multipart/form-data" method="POST">
    @csrf
    <div class="form-group">
        <label for="judul">Judul Film</label>
        <input type="text" class="form-control" name="judul" placeholder="Masukkan judul film">
        @error('judul')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        <label for="ringkasan">Ringkasan</label>
        <textarea class="form-control" name="ringkasan" cols="30" placeholder="Masukkan ringkasan"></textarea>
        @error('ringkasan')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        <label for="tahun">Tahun</label>
        {{-- <textarea class="form-control" name="tahun" cols="30" placeholder="Masukkan tahun"></textarea> --}}
        {{-- <input type="number" min="1950" max="{{date('Y')}}" name="tahun" id="tahun" class="form-control"> --}}
        {{-- <select name="" id="" class="form-control">
            @for ($i = date('Y'); $i >= 1950; $i--)
            <option>{{$i}}</option>
            @endfor
        </select> --}}

        <input type="text" class="yearpicker form-control" value="" name="tahun" />
        @error('tahun')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        <label>Genre</label>
        <select class="form-control" name="genre_id">
            <option value=""> -- pilih Genre --</option>
            @foreach ($genre as $genre)
            <option value="{{ $genre->id }}">{{ $genre->nama }}</option>
            @endforeach
        </select>
        @error('genre_id')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        <label>Poster</label>
        <input type="file" class="form-control-file" name="poster">
        @error('poster')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror
    </div>

    <button type="submit" class="btn btn-primary">Tambah</button>
</form>
</div>
@endsection


@push('style')
<link rel="stylesheet" href="{{asset('admin/plugins/yearpicker/yearpicker.css')}}">
@endpush

@push('script')
<script src="{{asset('admin/plugins/yearpicker/yearpicker.js')}}" async></script>
@endpush

resources/views/film/edit.blade.php
@extends('layouts.master')

@section('judul')
Halaman Tambah Film
@endsection

@section('konten')
<h2>Tambah Data Film</h2>
<form action="{{ route('film.update', ['film'=>$film->id]) }}" enctype="multipart/form-data" method="POST">
    @csrf
    @method('PUT')
    <div class="form-group">
        <label for="judul">Judul Film</label>
        <input type="text" class="form-control" name="judul" placeholder="Masukkan judul film"
            value="{{ $film->judul }}">
        @error('judul')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        <label for="ringkasan">Ringkasan</label>
        <textarea class="form-control" name="ringkasan" cols="30"
            placeholder="Masukkan ringkasan">{{ $film->ringkasan }}</textarea>
        @error('ringkasan')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        <label for="tahun">Tahun</label>
        {{-- <textarea class="form-control" name="tahun" cols="30" placeholder="Masukkan tahun"></textarea> --}}
        {{-- <input type="number" min="1950" max="{{date('Y')}}" name="tahun" id="tahun" class="form-control"> --}}
        {{-- <select name="" id="" class="form-control">
            @for ($i = date('Y'); $i >= 1950; $i--)
            <option>{{$i}}</option>
            @endfor
        </select> --}}

        <input type="text" class="yearpicker form-control" value="{{ $film->tahun }}" name="tahun" />
        @error('tahun')
        <div class="alert alert-danger">
            {{ $message }}
        </div>
        @enderror
    </div>

    <div class="form-group">
        <label>Genre</label>
        <select class="form-control" name="genre_id">
            <option value=""> -- pilih Genre --</option>
            @foreach ($genre as $genre)
            @if ($film->genre_id == $genre->id)
            <option value="{{$genre->id}}" selected>{{$genre->nama}}</option>
            @else
            <option value="{{$genre->id}}">{{$genre->nama}}</option>
            @endif
            @endforeach
        </select>
        @error('genre_id')
        <div class="alert alert-danger">
            {{ $message }}
        </div>s
        @enderror
    </div>

    <div class="form-group">
        <label>Poster</label>
        <input type="file" class="form-control-file" name="poster">
        <img src='{{ asset("uploads/film/$film->poster") }}' alt="" width="100px">
        <br>
        <small>Kosongkan jika tidak ingin mengganti file</small>
        @error('poster')
        <div class=" alert alert-danger">
            {{ $message }}
        </div>
        @enderror
    </div>

    <button type="submit" class="btn btn-primary">Update</button>
</form>
</div>
@endsection


@push('style')
<link rel="stylesheet" href="{{asset('admin/plugins/yearpicker/yearpicker.css')}}">
@endpush

@push('script')
<script src="{{asset('admin/plugins/yearpicker/yearpicker.js')}}" async></script>
@endpush

resources/views/film/index.blade.php
@extends('layouts.master')

@section('judul')
Halaman List Film
@endsection

@section('konten')
<a href="film/create" class="btn btn-primary mb-3">Tambah Data Film</a>

<div class="row">
    @foreach ($film as $film)
    <div class="col-4">
        <div class="card" style="width: 18rem;">
            <img src="{{ asset('uploads/film/'.$film->poster) }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h3 class="card-title mb-3">{{ $film->judul }}</h3>
                <p class="card-text">{{ $film->ringkasan }}</p>

                {{-- Detail --}}
                <a href="{{ route('film.show', ['film'=>$film->id]) }}" class="btn btn-primary">Detail</a>
                {{-- EDIT --}}
                {{-- <a href="/film/{{ $film->id }}/edit" class="btn btn-info">Edit</a> --}}
                <a href="{{ route('film.edit', ['film'=>$film->id]) }}" class="btn btn-info">Edit</a>
                <form method="POST" action="{{ route('film.destroy', ['film'=>$film->id]) }}" class="d-inline">
                    <button class="btn btn-danger" type="submit">Hapus</button>
                    @csrf
                    @method('DELETE')
                </form>
            </div>
        </div>
    </div>
    @endforeach
</div>

@endsection

resources/views/film/show.blade.php
@extends('layouts.master')

@section('judul')
Halaman List Film
@endsection

@section('konten')

<img src="{{ asset('uploads/film/'. $film->poster) }}" width="300">
<h2 class="mt-3">{{ $film->judul }}</h2>
<p>{{ $film->ringkasan }}</p>
@endsection